### ISSUE TITLE
Could you release the video dataset of Fis-V? Thanks! :)

### ISSUE THREAD

**Issue by qinghuannn** [loadder/MS_LSTM#1]
Could you release the video dataset of Fis-V?  
I want do experiment on the Fis-V dataset.
Thank you very much!  :)

**Comment by chmxu** [comment]
Hi. We have released the feature version of the dataset in the readme, which we think is enough for the experiment of scoring. We are not ready to release the video version dataset. Thanks for you attention to our work!
