### ISSUE TITLE
Can you please provide the pre-processing code for the video dataset?

### ISSUE THREAD

**Issue by NEMOlv** [loadder/MS_LSTM#4]
Hi！
I have seen your latest video dataset and would like to have access to the code you used to pre-process the dataset.

**Comment by chmxu** [comment]
Hi,
I don't remember the detail but I think I used this code [(link)](https://github.com/loadder/Video-Inference/blob/master/video.py) to extract the frames. You can try this. I used official C3D code to extract features.

**Comment by NEMOlv** [comment]
Thanks~
